trigger:
- main
- feature/*
stages:
  - stage: scan
    displayName: scan
    jobs:
      - job: terraforminit
        displayName: terraform init
        steps:
        - task: InfracostSetup@2
          inputs:
            apiKey: 'ico-tw0oH95vMImaw1AMin9xftV66ImsBg1R'
            version: '0.10.x'