trigger:
- main
- feature/*
stages:
  - stage: terraforminit
    displayName: terraform init
    jobs:
      - job: terraforminit
        displayName: terraform init
        steps:
        - task: CostGuardrails@1
          inputs:
            planPath: 'plan.json'